appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: R6ly139ESHzgl7Uty28vb24lrFxtYOTeBlUSk+m8ADE/XgdPkZtFOoKSSaFrQDuVz7YSHWWJYjQjCI2nnY6TxW35XaeecvMdOLoi8QQsTdrI0OlHjEobSfzRDxT5Ol7mRAspCJE/KNpzJyN3QmWpuNcy+mU/alyplnl10KXwMM1HnBoSRddT1jAB1CNFxyxOrMCESG5ATrvvdb/Xl4bTLgxd21cfqsrWbjAOm90wNBwW3PEo5L39ZiZHbwD4YeA3Ah7CiGnz3qrEfS4w70ghtc/jOl4fdw7MPbYQ96HSo9qhcMg/ICtMu4SVkfwb5vWDIniSbDqQ6lF0JySdu/b4zhiLo1TA/funlgnu+V5ZORK4nQ6i/DZYhRmKyYEQn75jfXiDh0l/KxSD6tznwNGC3jz3ntrTAQwkDzXd1pFv3/H2ZX2k9TYhSkzskMyGRbLWChqANVwiJQiPpItCpXTU8tXRa/rWqgMaMg5M8ZkzB9ynwNFi1g/V243z8fvKxAPsvOcB/zPnX/7Tr4oyPq8i/3LiJJS5kt1GmqlXFGg+GQXGGvOSJ8korU8ZkTLcZ3DTUxdWqkCKPEpZmhZDa8XS1ADK+ksRu2VeuF0oXEFC5pSMtlzd/jGp07wkrnaGv8fonz/qnMVYulyUYorsV7CssBzlEUF5sgHqtVVngjVf9yI=}
bot:
  automerge: true
